// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'df493b5cffdcbcedccbf82bacc92342c925de13ebc87f948f719876e08b09d1a'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Empresa: {
      readonly empresaId: CodecTypes['pg/int4@1']['output'];
      readonly cnpj: Varchar<18>;
      readonly creci: Varchar<20>;
      readonly nome: Varchar<50>;
    };
    readonly Gado: {
      readonly gadoId: CodecTypes['pg/int4@1']['output'];
      readonly negocioId: CodecTypes['pg/int4@1']['output'];
      readonly valorTotal: Numeric<15, 2> | null;
      readonly pesoArroba: Numeric<15, 2>;
      readonly pesoCalculo: Numeric<15, 2>;
      readonly pesoTotal: Numeric<15, 2>;
      readonly dataPesagem: CodecTypes['pg/timestamp-string@1']['output'] | null;
      readonly genero: Varchar<6>;
      readonly denominacao: Varchar<20>;
    };
    readonly Negocio: {
      readonly negocioId: CodecTypes['pg/int4@1']['output'];
      readonly empresaId: CodecTypes['pg/int4@1']['output'];
      readonly valorTotal: Numeric<15, 2> | null;
      readonly valorMedio: Numeric<15, 2> | null;
      readonly vendedor: Varchar<50>;
      readonly fazenda: Varchar<50>;
      readonly merchant: Varchar<50>;
      readonly comprador: Varchar<50> | null;
      readonly qtdAnimais: CodecTypes['pg/int4@1']['output'] | null;
      readonly rendimentoCarcaca: Numeric<5, 2>;
      readonly maisPesado: Numeric<15, 2> | null;
      readonly maisLeve: Numeric<15, 2> | null;
      readonly dataNegocio: CodecTypes['pg/timestamp-string@1']['output'];
      readonly comissao: Numeric<15, 2>;
      readonly valorArroba: Numeric<15, 2>;
      readonly modalidade: Varchar<20>;
    };
    readonly Usuario: {
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly empresaId: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
      readonly sobrenome: Varchar<50>;
      readonly email: Varchar<254>;
      readonly senha: Varchar<255>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Empresa: {
      readonly empresaId: CodecTypes['pg/int4@1']['input'];
      readonly cnpj: CodecTypes['sql/varchar@1']['input'];
      readonly creci: CodecTypes['sql/varchar@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Gado: {
      readonly gadoId: CodecTypes['pg/int4@1']['input'];
      readonly negocioId: CodecTypes['pg/int4@1']['input'];
      readonly valorTotal: CodecTypes['pg/numeric@1']['input'] | null;
      readonly pesoArroba: CodecTypes['pg/numeric@1']['input'];
      readonly pesoCalculo: CodecTypes['pg/numeric@1']['input'];
      readonly pesoTotal: CodecTypes['pg/numeric@1']['input'];
      readonly dataPesagem: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly genero: CodecTypes['sql/varchar@1']['input'];
      readonly denominacao: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Negocio: {
      readonly negocioId: CodecTypes['pg/int4@1']['input'];
      readonly empresaId: CodecTypes['pg/int4@1']['input'];
      readonly valorTotal: CodecTypes['pg/numeric@1']['input'] | null;
      readonly valorMedio: CodecTypes['pg/numeric@1']['input'] | null;
      readonly vendedor: CodecTypes['sql/varchar@1']['input'];
      readonly fazenda: CodecTypes['sql/varchar@1']['input'];
      readonly merchant: CodecTypes['sql/varchar@1']['input'];
      readonly comprador: CodecTypes['sql/varchar@1']['input'] | null;
      readonly qtdAnimais: CodecTypes['pg/int4@1']['input'] | null;
      readonly rendimentoCarcaca: CodecTypes['pg/numeric@1']['input'];
      readonly maisPesado: CodecTypes['pg/numeric@1']['input'] | null;
      readonly maisLeve: CodecTypes['pg/numeric@1']['input'] | null;
      readonly dataNegocio: CodecTypes['pg/timestamp-string@1']['input'];
      readonly comissao: CodecTypes['pg/numeric@1']['input'];
      readonly valorArroba: CodecTypes['pg/numeric@1']['input'];
      readonly modalidade: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Usuario: {
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly empresaId: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly sobrenome: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly senha: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly empresa: {
      readonly cnpj: Varchar<18>;
      readonly creci: Varchar<20>;
      readonly empresa_id: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
    };
    readonly gado: {
      readonly data_pesagem: CodecTypes['pg/timestamp-string@1']['output'] | null;
      readonly denominacao: Varchar<20>;
      readonly gado_id: CodecTypes['pg/int4@1']['output'];
      readonly genero: Varchar<6>;
      readonly negocio_id: CodecTypes['pg/int4@1']['output'];
      readonly peso_arroba: Numeric<15, 2>;
      readonly peso_calculo: Numeric<15, 2>;
      readonly peso_total: Numeric<15, 2>;
      readonly valor_total: Numeric<15, 2> | null;
    };
    readonly negocio: {
      readonly comissao: Numeric<15, 2>;
      readonly comprador: Varchar<50> | null;
      readonly data_negocio: CodecTypes['pg/timestamp-string@1']['output'];
      readonly empresa_id: CodecTypes['pg/int4@1']['output'];
      readonly fazenda: Varchar<50>;
      readonly mais_leve: Numeric<15, 2> | null;
      readonly mais_pesado: Numeric<15, 2> | null;
      readonly merchant: Varchar<50>;
      readonly modalidade: Varchar<20>;
      readonly negocio_id: CodecTypes['pg/int4@1']['output'];
      readonly qtd_animais: CodecTypes['pg/int4@1']['output'] | null;
      readonly rendimento_carcaca: Numeric<5, 2>;
      readonly valor_arroba: Numeric<15, 2>;
      readonly valor_medio: Numeric<15, 2> | null;
      readonly valor_total: Numeric<15, 2> | null;
      readonly vendedor: Varchar<50>;
    };
    readonly usuario: {
      readonly email: Varchar<254>;
      readonly empresa_id: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
      readonly senha: Varchar<255>;
      readonly sobrenome: Varchar<50>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly empresa: {
      readonly cnpj: CodecTypes['sql/varchar@1']['input'];
      readonly creci: CodecTypes['sql/varchar@1']['input'];
      readonly empresa_id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
    };
    readonly gado: {
      readonly data_pesagem: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly denominacao: CodecTypes['sql/varchar@1']['input'];
      readonly gado_id: CodecTypes['pg/int4@1']['input'];
      readonly genero: CodecTypes['sql/varchar@1']['input'];
      readonly negocio_id: CodecTypes['pg/int4@1']['input'];
      readonly peso_arroba: CodecTypes['pg/numeric@1']['input'];
      readonly peso_calculo: CodecTypes['pg/numeric@1']['input'];
      readonly peso_total: CodecTypes['pg/numeric@1']['input'];
      readonly valor_total: CodecTypes['pg/numeric@1']['input'] | null;
    };
    readonly negocio: {
      readonly comissao: CodecTypes['pg/numeric@1']['input'];
      readonly comprador: CodecTypes['sql/varchar@1']['input'] | null;
      readonly data_negocio: CodecTypes['pg/timestamp-string@1']['input'];
      readonly empresa_id: CodecTypes['pg/int4@1']['input'];
      readonly fazenda: CodecTypes['sql/varchar@1']['input'];
      readonly mais_leve: CodecTypes['pg/numeric@1']['input'] | null;
      readonly mais_pesado: CodecTypes['pg/numeric@1']['input'] | null;
      readonly merchant: CodecTypes['sql/varchar@1']['input'];
      readonly modalidade: CodecTypes['sql/varchar@1']['input'];
      readonly negocio_id: CodecTypes['pg/int4@1']['input'];
      readonly qtd_animais: CodecTypes['pg/int4@1']['input'] | null;
      readonly rendimento_carcaca: CodecTypes['pg/numeric@1']['input'];
      readonly valor_arroba: CodecTypes['pg/numeric@1']['input'];
      readonly valor_medio: CodecTypes['pg/numeric@1']['input'] | null;
      readonly valor_total: CodecTypes['pg/numeric@1']['input'] | null;
      readonly vendedor: CodecTypes['sql/varchar@1']['input'];
    };
    readonly usuario: {
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly empresa_id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly senha: CodecTypes['sql/varchar@1']['input'];
      readonly sobrenome: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly empresa: {
              columns: {
                readonly empresa_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly cnpj: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 18 };
                };
                readonly creci: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: {
                readonly columns: readonly ['empresa_id'];
                readonly name: 'empresa_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly gado: {
              columns: {
                readonly gado_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly negocio_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly valor_total: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly peso_arroba: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly peso_calculo: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly peso_total: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly data_pesagem: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                };
                readonly genero: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 6 };
                };
                readonly denominacao: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 20 };
                };
              };
              primaryKey: { readonly columns: readonly ['gado_id']; readonly name: 'gado_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'gado';
                    readonly columns: readonly ['negocio_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'negocio';
                    readonly columns: readonly ['negocio_id'];
                  };
                  readonly name: 'gado_negocio_id_fkey';
                },
              ];
            };
            readonly negocio: {
              columns: {
                readonly negocio_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly empresa_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly valor_total: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly valor_medio: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly vendedor: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly fazenda: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly merchant: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly comprador: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly qtd_animais: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly rendimento_carcaca: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 5; readonly scale: 2 };
                };
                readonly mais_pesado: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly mais_leve: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly data_negocio: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                };
                readonly comissao: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly valor_arroba: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
                readonly modalidade: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 20 };
                };
              };
              primaryKey: {
                readonly columns: readonly ['negocio_id'];
                readonly name: 'negocio_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'negocio';
                    readonly columns: readonly ['empresa_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'empresa';
                    readonly columns: readonly ['empresa_id'];
                  };
                  readonly name: 'negocio_empresa_id_fkey';
                },
              ];
            };
            readonly usuario: {
              columns: {
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly empresa_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly sobrenome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 254 };
                };
                readonly senha: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['user_id']; readonly name: 'usuario_pkey' };
              uniques: readonly [
                { readonly columns: readonly ['email']; readonly name: 'usuario_email_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['empresa_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'empresa';
                    readonly columns: readonly ['empresa_id'];
                  };
                  readonly name: 'usuario_empresa_id_fkey';
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly empresa: { readonly namespace: 'public' & NamespaceId; readonly model: 'Empresa' };
    readonly negocio: { readonly namespace: 'public' & NamespaceId; readonly model: 'Negocio' };
    readonly gado: { readonly namespace: 'public' & NamespaceId; readonly model: 'Gado' };
    readonly usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Empresa: {
            readonly fields: {
              readonly empresaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cnpj: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 18 };
                };
              };
              readonly creci: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly negocios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Negocio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['empresaId'];
                  readonly targetFields: readonly ['empresaId'];
                };
              };
              readonly usuarios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['empresaId'];
                  readonly targetFields: readonly ['empresaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'empresa';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly empresaId: { readonly column: 'empresa_id' };
                readonly cnpj: { readonly column: 'cnpj' };
                readonly creci: { readonly column: 'creci' };
                readonly nome: { readonly column: 'nome' };
              };
            };
          };
          readonly Gado: {
            readonly fields: {
              readonly gadoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly negocioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly valorTotal: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly pesoArroba: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly pesoCalculo: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly pesoTotal: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly dataPesagem: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
              readonly genero: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 6 };
                };
              };
              readonly denominacao: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
            };
            readonly relations: {
              readonly negocio: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Negocio';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['negocioId'];
                  readonly targetFields: readonly ['negocioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'gado';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly gadoId: { readonly column: 'gado_id' };
                readonly negocioId: { readonly column: 'negocio_id' };
                readonly valorTotal: { readonly column: 'valor_total' };
                readonly pesoArroba: { readonly column: 'peso_arroba' };
                readonly pesoCalculo: { readonly column: 'peso_calculo' };
                readonly pesoTotal: { readonly column: 'peso_total' };
                readonly dataPesagem: { readonly column: 'data_pesagem' };
                readonly genero: { readonly column: 'genero' };
                readonly denominacao: { readonly column: 'denominacao' };
              };
            };
          };
          readonly Negocio: {
            readonly fields: {
              readonly negocioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly empresaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly valorTotal: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly valorMedio: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly vendedor: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly fazenda: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly merchant: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly comprador: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly qtdAnimais: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly rendimentoCarcaca: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 5; readonly scale: 2 };
                };
              };
              readonly maisPesado: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly maisLeve: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly dataNegocio: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
              readonly comissao: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly valorArroba: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 15; readonly scale: 2 };
                };
              };
              readonly modalidade: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
            };
            readonly relations: {
              readonly empresa: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Empresa';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['empresaId'];
                  readonly targetFields: readonly ['empresaId'];
                };
              };
              readonly gados: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Gado' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['negocioId'];
                  readonly targetFields: readonly ['negocioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'negocio';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly negocioId: { readonly column: 'negocio_id' };
                readonly empresaId: { readonly column: 'empresa_id' };
                readonly valorTotal: { readonly column: 'valor_total' };
                readonly valorMedio: { readonly column: 'valor_medio' };
                readonly vendedor: { readonly column: 'vendedor' };
                readonly fazenda: { readonly column: 'fazenda' };
                readonly merchant: { readonly column: 'merchant' };
                readonly comprador: { readonly column: 'comprador' };
                readonly qtdAnimais: { readonly column: 'qtd_animais' };
                readonly rendimentoCarcaca: { readonly column: 'rendimento_carcaca' };
                readonly maisPesado: { readonly column: 'mais_pesado' };
                readonly maisLeve: { readonly column: 'mais_leve' };
                readonly dataNegocio: { readonly column: 'data_negocio' };
                readonly comissao: { readonly column: 'comissao' };
                readonly valorArroba: { readonly column: 'valor_arroba' };
                readonly modalidade: { readonly column: 'modalidade' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly empresaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly sobrenome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 254 };
                };
              };
              readonly senha: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly empresa: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Empresa';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['empresaId'];
                  readonly targetFields: readonly ['empresaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly userId: { readonly column: 'user_id' };
                readonly empresaId: { readonly column: 'empresa_id' };
                readonly nome: { readonly column: 'nome' };
                readonly sobrenome: { readonly column: 'sobrenome' };
                readonly email: { readonly column: 'email' };
                readonly senha: { readonly column: 'senha' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
